### ISSUE TITLE
Changing background color of the header / banner

### ISSUE THREAD

**Issue by xmatic** [IFBook/commentpress-core#50]
I don't remember how I did it, but while playing around with Wordpress + Commentpress, I intentionally changed the header background color. Thing is, I want to change it again, and can't figure out how anymore. How does one do this? Thanks.

**Comment by christianwach** [comment]
It's under 'Theme Customisation' in the Settings --> CommentPress Core admin page

**Comment by xmatic** [comment]
Thank you! That worked.
