### ISSUE TITLE
Uncaught Type Error - Wordpress 4.3

### ISSUE THREAD

**Issue by vicktor3** [IFBook/commentpress-core#56]
After loading the plugin and activating the theme for Comment Press an error appears and renders the comment functionality and theme layout broken. 

Here is the error message I receive in Chrome. It stems from `jquery.commentpress.min.js?ver=3.8.2:1`

```
 Uncaught TypeError: Cannot read property 'viewport' of undefined
     (anonymous function) @ jquery.commentpress.min.js?ver=3.8.2:1
     m.event.dispatch @ jquery.js?ver=1.11.3:4
     m.event.add.r.handle @ jquery.js?ver=1.11.3:4
```
I am on the recently updated Wordpress version 4.3. If I figure out a solution I will either close the issue (in the case of installation error) or create a pull request.

**Comment by christianwach** [comment]
Thanks for the report @vicktor3 - I'm unable to reproduce on WP 4.3 but...

* Which CommentPress theme did you activate?
* Can you set `define('SCRIPT_DEBUG', true);` in wp-config.php and see if the error persists?
* Are there any other plugins active?

The above will help me try and reproduce.

**Comment by vicktor3** [comment]
I activated the Modern CommentPress Theme. I went ahead and set `SCRIPT_DEBUG=true` and removed all plugins but the error persisted. I did some more research and this may be an issue with Microsoft WebMatrix and not the theme. I will verify later tonight.

**Comment by christianwach** [comment]
I think I've seen something like this before with Windows-based servers - it seems that the family of WordPress functions that include 'get_stylesheet_directory()', 'get_stylesheet_directory_uri()' and so on return the wrong path to the resources being targeted. This would explain your error, which is related to calling a Javascript method in a theme script. It would be interesting to hear if you solve this and how you did so if you succeed.

**Comment by vicktor3** [comment]
I confirmed that the issue is with Windows webmatrix. I am also curious to fix the issue and will create a pull request if I am able to figure it out. 

I will close the issue since it appears to be with the way Windows webmatrix or IIS serves the content not Comment Press.

**Comment by christianwach** [comment]
@vicktor3 Thanks for the confirmation. FWIW, I think others worked around the issue by moving the theme folders to the 'wp-content/themes' directory. This workaround will mean you'll have to replace the theme folders each time there's a plugin update, but it's worth a shot.
