### ISSUE TITLE
AJAX error

### ISSUE THREAD

**Issue by canferman** [IFBook/commentpress-core#63]
when someone comment on a paragrapf, a dialog box from chorme and firefox says:
AJAX error! TypeError: Cannot read property 'header' of undefined

when i deleted the 1322. line of jquery.commentpress.js 

`offset: CommentPress.theme.header.get_offset()`

the dialog box doesnt appears

**Comment by christianwach** [comment]
Which theme are you using?

**Comment by canferman** [comment]
commentpress modern

**Comment by christianwach** [comment]
ok... and which version of CommentPress?

**Comment by canferman** [comment]
3.8.4

and also,

when i looking with "inspect element"
if i click on a paragraph, inspect element console says:
```
Uncaught TypeError: Cannot read property 'viewport' of undefined
(anonymous function)	@	jquery.commentpress.min.js?ver=3.8.4:859
n.event.dispatch	@	jquery.js?ver=1.11.3:3
r.handle	@	jquery.js?ver=1.11.3:3
```
after i deleted the 859. line of jquery.commentpress.js, thiss error dissapears

**Comment by christianwach** [comment]
Hmm, well I'm not sure deleting bits of Javascript is going to solve the issue ;-) Do you have a URL I can look at?

**Comment by canferman** [comment]
i know that, but i m not a master of js =)

benceboyle.net
user: cp-developer
pass: 123456

you can login with this info, and try to comment to some paragraph of random post.

i will delete this account after some minutes =)

**Comment by christianwach** [comment]
I'm in and have changed the pwd.
Can you add `define('SCRIPT_DEBUG', true);` to your wp-config.php please?

**Comment by canferman** [comment]
ok i changed it true

**Comment by christianwach** [comment]
You have an [old version of the theme](http://benceboyle.net/wp-content/themes/commentpress-modern/style.css) in the 'wp-content/themes'. The plugin supplies its own theme inside the plugin's own directory. You shouldn't duplicate it in 'wp-content/themes'. If you want to restyle things, I recommend that you create a child theme.

**Comment by canferman** [comment]
ok, thanks a lot, 
i deleted the theme in commentpress plugin folder because of some other errors.
i dont kown how can edit a child theme but i will try...
i will update my theme folder, i changed only the css files

thank you so much

**Comment by christianwach** [comment]
HTH :-)

**Comment by canferman** [comment]
its looks like my used theme commentpress-modern is the latest version of theme:
[https://plugins.svn.wordpress.org/commentpress-core/tags/3.8.4/themes/commentpress-modern/style.css](url)
version 3.5

i will transfer my theme files to  ../plugin/comment-press/themes

**Comment by christianwach** [comment]
@canferman I would put your theme to one side for the moment. It may *look* like a current version but it isn't. Save it somewhere outside your WordPress install. Now re-install CommentPress Core from the WordPress repo by downloading and overwriting the plugin's folder.

Next, grab a copy of this [sample child theme](https://github.com/christianwach/commentpress-modern-child) that you can build upon. Unzip and put the resulting (renamed as per the instructions) folder in 'wp-content/themes'. Activate it and start overriding the look and feel of the CommentPress Modern Theme by transferring your amends to the 'style-overrides.css' file. You can also dequeue a couple of other CommentPress stylesheets by uncommenting a couple of lines in the child theme's functions.php file if they're not needed.
