### ISSUE TITLE
In-place editor escapes characters on edit

### ISSUE THREAD

**Issue by WhatTheDickens** [IFBook/commentpress-core#83]
After one edits a comment in the new (3.9.12) in-place editor, single and double quotes (which are handled fine in the initial post) display as escaped. I.e., the *saved* version of the edited comment contains `\'` and `\"` for every `'` and `"` in the initial post.. The only way to remove `\` is to go to the back-end editor.

**Comment by christianwach** [comment]
Thanks for catching this @WhatTheDickens - d8f5182adf752dd5b6957e101a528bf65a16973d should fix this. I'll push to the WordPress directory in due course.
