### ISSUE TITLE
path variable becomes absolute when activating Commentpress

### ISSUE THREAD

**Issue by SavantasNL** [IFBook/commentpress-core#87]
Hi, I've got a local installation (within Windows, Xampp) with an copy of a public site. As soon as I install and activate the CommentPress plugin, my site looks broken. When looking at the page source I see some paths to css and js links show absolute Windows paths instead of a relative path:

For example:

````html
<link rel='stylesheet' id='cp_colours_css-css'  href='http://localhost/wordpress_gborC:xampphtdocswordpress_gborwp-contentpluginscommentpress-core/themes/commentpress-modern/assets/css/colours-01.min.css?ver=3.9.12' type='text/css' media='all' />
<link rel='stylesheet' id='cp_buddypress_css-css'  href='http://localhost/wordpress_gborC:xampphtdocswordpress_gborwp-contentpluginscommentpress-core/themes/commentpress-modern/assets/css/bp-overrides.min.css?ver=3.9.12' type='text/css' media='all' />
<link rel='stylesheet' id='cp_print_css-css'  href='http://localhost/wordpress_gborC:xampphtdocswordpress_gborwp-contentpluginscommentpress-core/themes/commentpress-modern/assets/css/print.min.css?ver=3.9.12' type='text/css' media='print' />```


where C:xampphtdocswordpressgbor is the absolute path (C:\xampp\htdocs\wordpress_gbor)

**Comment by SavantasNL** [comment]
Going through the database (wp_options) I found _site_transient_theme_roots, _site_transient_itsec_wp_upload_dir, template_root and stylesheet_root with the absolute link. Shouldn't these have relative paths instead?

**Comment by christianwach** [comment]
@SavantasNL Thanks for the report. 

CommentPress doesn't do any parsing of these URLs. What it does is to [declare a custom theme directory](https://github.com/IFBook/commentpress-core/blob/d868f13caaeb446d475480fa4d83b0991f1d1b09/commentpress-core.php#L386) and then build the URLs via the `get_template_directory_uri()` WordPress function. Here's [the print stylesheet enqueue code](https://github.com/IFBook/commentpress-core/blob/d868f13caaeb446d475480fa4d83b0991f1d1b09/themes/commentpress-modern/functions.php#L301-L308) for example.

What you're seeing, therefore, could be either:

- A misconfiguration of your development environment or
- Some kind of incompatibility in WordPress core - perhaps in [`search_theme_directories()`](https://developer.wordpress.org/reference/functions/search_theme_directories/) or in [`plugin_dir_path()`](https://developer.wordpress.org/reference/functions/plugin_dir_path/).

You'd have to trace backwards from the call to `get_template_directory_uri()` to see what's really going on.

> Shouldn't these have relative paths instead?

WordPress practically never uses relative URLs. There's almost endless discussion about why it doesn't around the internet, so I won't add to it here!

Cheers, Christian
