### ISSUE TITLE
Bundled themes are not visible under "Appearance > Themes" if commentpress-core is not network-activated

### ISSUE THREAD

**Issue by r-a-y** [IFBook/commentpress-core#89]
Hi Christian,

We're running CommentPress on the Commons, but not network-activated.

When CP isn't network-activated, but only activated on a site, CP's bundled themes are not visible because those themes are not network-enabled. We worked around this with the following code snippet:

```
add_filter( 'allowed_themes', function( $retval ) {
	$retval['commentpress-flat']   = 1;
	$retval['commentpress-modern'] = 1;
	$retval['commentpress-theme']  = 1;
	return $retval;
} );
```

Maybe you can add some variation of this snippet into the codebase?

**Comment by christianwach** [comment]
@r-a-y Thanks for noting this. FWIW I've always used child themes which IIRC don't seem to care whether the parent theme is active or not. 

Before I go ahead and add this, it seems that there a confusing set of filters for this:

* `network_allowed_themes`
* `site_allowed_themes`
* `allowed_themes`

Was there a reason you chose the latter?

**Comment by r-a-y** [comment]
All the filters you listed work.

The difference is in the firing order: https://github.com/WordPress/WordPress/blob/c81db1f6e64262b6711bc5f20894c7d40505d0c1/wp-includes/class-wp-theme.php#L1457-L1458

- `allowed_themes` runs first
- `network_allowed_themes` runs second
- `site_allowed_themes` runs last

I think `network_allowed_themes` might be better as it explains what we want to do. We want to allow CommentPress themes to be visible on multisite installs when the plugin is activated.

But you can make a case for any of the filters :)

**Comment by christianwach** [comment]
@r-a-y Latest release on WordPress Plugin Directory implements this fix. Please re-open if you find anything amiss. Thanks!
