### ISSUE TITLE
Wrong conditional statement here

### ISSUE THREAD

**Issue by ReyazBeigh** [IFBook/commentpress-core#97]
Please cross check if the statement if it is correct. 

https://github.com/IFBook/commentpress-core/blob/ca275b910241725afea348248db83d2e5de59326/includes/core/assets/includes/theme/theme-comments.php#L520

Because of this issue, it is showing all the comments in the activity section as  "Comment awaiting moderation", after fixing it on my production server. the issue went away.

**Comment by christianwach** [comment]
@ReyazBeigh Already fixed in my dev repo:

https://github.com/christianwach/commentpress-core/commit/de5379da603d7489d19b2adc49e4fcfa247bd1c7

Thanks for confirming - I'll merge in due course.
